version: '3.7'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode.emr.1234.com
    ports:
      - "50070:50070"  # NameNode Web UI
    environment:
      - CLUSTER_NAME=hdfs-cluster
      - KRB5_REALM=EMR.1234.COM
      - KRB5_KDC=kdc1  # 替换为您的 KDC 服务器地址
    volumes:
      - ./kerberos/krb5.conf:/etc/krb5.conf
      - ./kerberos/nn.keytab:/etc/hadoop/nn.keytab  # 挂载 NameNode 的 Keytab 文件
      - ./hadoop/core-site.xml:/etc/hadoop/core-site.xml  # 挂载 Hadoop 配置文件
      - ./hadoop/hdfs-site.xml:/etc/hadoop/hdfs-site.xml
      - ./hadoop/ssl-server.xml:/etc/hadoop/ssl-server.xml
      - ./hadoop/ssl-client.xml:/etc/hadoop/ssl-client.xml
      - ./ca/bash/truststore:/etc/hadoop/truststore
      - ./ca/bash/keystore:/etc/hadoop/keystore
      - namenode-data:/hadoop/dfs/name  # NameNode 数据卷
    networks:
      hadoop-net:
        ipv4_address: 172.20.0.21
    extra_hosts: 
      - "kdc1:172.20.0.2"
      - "kdc2:172.20.0.3"
      - "namenode.emr.1234.com:172.20.0.21"
      - "datanode.emr.1234.com:172.20.0.22"

  datanode:
    # image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    image: my-datanode:v1
    # build:
    #   context: .
    #   dockerfile: Dockerfile-datanode1  # 使用自定义 Dockerfile
    container_name: datanode
    hostname: datanode.emr.1234.com
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode.emr.1234.com:9000
      - KRB5_REALM=EMR.1234.COM
      - KRB5_KDC=kdc1  # 替换为您的 KDC 服务器地址
    volumes:
      - ./kerberos/krb5.conf:/etc/krb5.conf
      - ./kerberos/dn.keytab:/etc/hadoop/dn.keytab  # 挂载 DataNode 的 Keytab 文件
      - ./hadoop/core-site.xml:/etc/hadoop/core-site.xml  # 挂载 Hadoop 配置文件
      - ./hadoop/hdfs-site.xml:/etc/hadoop/hdfs-site.xml
      - ./hadoop/ssl-server.xml:/etc/hadoop/ssl-server.xml
      - ./hadoop/ssl-client.xml:/etc/hadoop/ssl-client.xml
      - ./ca/bash/truststore:/etc/hadoop/truststore
      - ./ca/bash/keystore:/etc/hadoop/keystore
      # - ./hadoop/hadoop-env.sh:/etc/hadoop/hadoop-env.sh
      - datanode-data:/hadoop/dfs/data  # DataNode 数据卷
    tmpfs:
      - /tmp
    networks:
      hadoop-net:
        ipv4_address: 172.20.0.22
    extra_hosts: 
      - "kdc1:172.20.0.2"
      - "kdc2:172.20.0.3"
      - "namenode.emr.1234.com:172.20.0.21"
      - "datanode.emr.1234.com:172.20.0.22"
    depends_on:
      - namenode

  # resourcemanager:
  #   image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
  #   container_name: resourcemanager
  #   hostname: resourcemanager.emr.1234.com
  #   environment:
  #     - CORE_CONF_fs_defaultFS=hdfs://namenode.emr.1234.com:9000
  #     - KRB5_REALM=EMR.1234.COM
  #     - KRB5_KDC=kdc1  # 替换为您的 KDC 服务器地址
  #   ports:
  #     - "8088:8088"  # ResourceManager Web UI
  #   volumes:
  #     - ./kerberos/rm.keytab:/etc/hadoop/rm.keytab  # 挂载 ResourceManager 的 Keytab 文件
  #     - ./hadoop/core-site.xml:/etc/hadoop/core-site.xml  # 挂载 Hadoop 配置文件
  #     - ./hadoop/hdfs-site.xml:/etc/hadoop/hdfs-site.xml
  #   networks:
  #     - hadoop-net
  #   depends_on:
  #     - namenode
  #     - datanode

  # nodemanager:
  #   image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
  #   container_name: nodemanager
  #   hostname: nodemanager.emr.1234.com
  #   environment:
  #     - CORE_CONF_fs_defaultFS=hdfs://namenode.emr.1234.com:9000
  #     - KRB5_REALM=EMR.1234.COM
  #     - KRB5_KDC=kdc1  # 替换为您的 KDC 服务器地址
  #   volumes:
  #     - ./kerberos/nm.keytab:/etc/hadoop/nm.keytab  # 挂载 NodeManager 的 Keytab 文件
  #     - ./hadoop/core-site.xml:/etc/hadoop/core-site.xml  # 挂载 Hadoop 配置文件
  #     - ./hadoop/hdfs-site.xml:/etc/hadoop/hdfs-site.xml
  #   networks:
  #     - hadoop-net
  #   depends_on:
  #     - resourcemanager

  # historyserver:
  #   image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
  #   container_name: historyserver
  #   hostname: historyserver.emr.1234.com
  #   environment:
  #     - CORE_CONF_fs_defaultFS=hdfs://namenode.emr.1234.com:9000
  #     - KRB5_REALM=EMR.1234.COM
  #     - KRB5_KDC=kdc1  # 替换为您的 KDC 服务器地址
  #   ports:
  #     - "8188:8188"  # HistoryServer Web UI
  #   volumes:
  #     - ./hs.keytab:/etc/hadoop/hs.keytab  # 挂载 HistoryServer 的 Keytab 文件
  #     - ./chadoop/ore-site.xml:/etc/hadoop/core-site.xml  # 挂载 Hadoop 配置文件
  #     - ./hadoop/hdfs-site.xml:/etc/hadoop/hdfs-site.xml
  #   networks:
  #     - hadoop-net
  #   depends_on:
  #     - resourcemanager

volumes:
  namenode-data:
  datanode-data:

networks:
  hadoop-net:
    external: true  # 声明使用外部网络
    name: advance_kerberos-net  # 自定义网络名称
    driver: bridge        # 网络驱动类型（bridge 是默认值）