version: "3"
services:
  fe:
    image: apache-doris:2.1.5-fe
    hostname: fe
    environment:
     - FE_SERVERS=fe1:10.0.5.2:9010
     - FE_ID=1
    volumes:
     - /data/fe/doris-meta/:/opt/apache-doris/fe/doris-meta/
     - /data/fe/log/:/opt/apache-doris/fe/log/
    network_mode: host
  be:
    image: apache-doris:2.1.5-be
    hostname: be
    environment:
     - FE_SERVERS=fe1:10.0.5.2:9010
     - BE_ADDR=10.0.5.2:9050
    volumes:
     - /data/be/storage/:/opt/apache-doris/be/storage/
     - /data/be/script/:/docker-entrypoint-initdb.d/
    depends_on:
      - fe
    network_mode: host